---
- hosts: all

  tasks:

    - name: Create VM from template
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        clone: "{{ template_id }}"
        full: true
        memory: "{{ memory }}"
        cores: "{{ cores }}"
        boot: c
        bootdisk: scsi0
        agent: 1

    - name: Configure Cloud-Init for the VM
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ vm_id }}"
        ciuser: "ubuntu"                   # Default Ubuntu Cloud-Init user
        cipassword: "ubuntu_password"      # Password for the Cloud-Init user
        ipconfig: ip=dhcp

    - name: Start the VM
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ vm_id }}"
        state: started