---
- hosts: all
  vars:
    api_user: "{{ api_user }}"
    proxmox_host: "{{ proxmox_host }}"
    proxmox_token_id: "{{ proxmox_token_id }}"
    proxmox_token_secret: "{{ proxmox_token_secret }}"
    node: "{{ node }}"
    template_id: "{{ template_id }}"
    vm_id: "{{ vm_id }}"
    vm_name: "{{ vm_name }}"
    memory: "{{ memory }}"
    cores: "{{ cores }}"
    cpus: "{{ cpus }}"
    disk_size: "{{ disk_size }}"
    ci_user: "{{ ci_user }}"
    ci_password: "{{ ci_password }}"
    ipconfig: "{{ ipconfig }}"
    nameserver: "{{ nameserver }}"
    sshkeys: "{{ ssh_key }}"

  tasks:
    - name: Create VM from template
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        clone: "{{ template_id }}"
        full: yes
        bootdisk: scsi0
        agent: 1
        onboot: true
        storage: local-lvm
        timeout: 1200

    - name: Grow VM disk
      community.general.proxmox_disk:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        vmid: "{{ template_id }}"
        disk: scsi0
        size: "{{ disk_size }}"
        state: resized

    - name: Configure Memory and CPU/Core for the VM
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ template_id }}"
        memory: "{{ memory }}"
        cores: "{{ cores }}"
        sockets: "{{ cpus }}"
        update: true

    - name: Configure Cloud-Init for the VM
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ template_id }}"
        ciuser: "{{ ci_user }}"
        cipassword: "{{ ci_password }}"
        sshkeys: "{{ ssh_key }}"
        ipconfig:
          ipconfig0: "{{ ipconfig }}"
        update: true

    - name: Start the VM
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ template_id }}"
        state: started