---
- hosts: all

  tasks:

    - name: Create VM from template
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        clone: "{{ template_id }}"
        full: true
        memory: "{{ memory }}"
        cores: "{{ cores }}"
        scsi: "local-lvm:{{ disk_size }}"  # Disk setup
        net:
          - model: virtio                  # Use Virtio for network interface
            bridge: vmbr0                  # Network bridge for Proxmox
        boot: c                            # Boot from disk
        bootdisk: scsi0                    # Boot disk set as scsi0
        agent: 1                           # Enable QEMU agent

    - name: Configure Cloud-Init for the VM
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ vm_id }}"
        ciuser: "ubuntu"                   # Default Ubuntu Cloud-Init user
        cipassword: "ubuntu_password"      # Password for the Cloud-Init user
        nameserver: "8.8.8.8"
        searchdomain: "local"
        ipconfig0: ip=dhcp

    - name: Start the VM
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ vm_id }}"
        state: started