---
- hosts: all

  tasks:

    - name: Create VM from template
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        clone: "{{ template_id }}"
        full: yes
        memory: "{{ memory }}"
        cores: "{{ cores }}"
        sockets: "{{ cpus }}"
        bootdisk: scsi0
        agent: 1
        onboot: true
        storage: local-lvm

    - name: Grow VM disk
      community.general.proxmox_disk:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        vmid: "{{ template_id }}"
        disk: scsi0
        size: "{{ disk_size }}"
        state: resized

    - name: Configure Cloud-Init for the VM
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ template_id }}"
        ciuser: "{{ ci_user }}"
        cipassword: "{{ ci_password }}"
        ipconfig: 
          - "{{ ipconfig }}"
        nameservers: "{{ nameserver }}"
        update: true

    - name: Start the VM
      community.general.proxmox_kvm:
        node: "{{ node }}"
        api_host: "{{ proxmox_host }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_user: "{{ api_user }}"
        vmid: "{{ template_id }}"
        state: started