- name: Install qemu-guest-agent on all specified hosts
  hosts: all
  become: yes

  tasks:
    - name: Ensure qemu-guest-agent is installed
      apt:
        name: qemu-guest-agent
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure qemu-guest-agent is installed on RedHat/CentOS
      yum:
        name: qemu-guest-agent
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable qemu-guest-agent service
      systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started